# Generated by Django 4.1.3 on 2024-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'Высокий приоритет'), ('medium', 'Средний приоритет'), ('low', 'Низкий приоритет')], max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
